### ISSUE TITLE
Bottom-up features for images link is not available

### ISSUE THREAD

**Issue by yulu0724** [Yinan-Zhao/AoANet_VizWiz#5]
Hi, I found the link of pre-extracted bottom-up features is not available, could you please provide the link again? Thanks!

**Comment by Yinan-Zhao** [comment]
It is in the following link. This link is provided in the readme of data/

http://ivc.ischool.utexas.edu/VizWiz_final/caption/AoANet_VizWiz/data/tsv.zip
